# Generated by Django 3.1.3 on 2020-11-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DatesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Поручение', 'Поручение'), ('Письмо', 'Письмо'), ('Обращение', 'Обращение'), ('Фишка', 'Фишка')], max_length=500, null=True, verbose_name='Вид')),
                ('sign', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подпись')),
                ('contract_id_unique', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Номер')),
                ('task_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('content', models.CharField(blank=True, max_length=700, null=True, verbose_name='Содержание')),
                ('responsible_user', models.CharField(blank=True, max_length=300, null=True, verbose_name='Исполнитель')),
                ('task_deadline', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('result', models.CharField(blank=True, help_text='Для начальника', max_length=300, null=True, verbose_name='Результат')),
                ('verification', models.CharField(blank=True, choices=[('Не сделано', 'Активный'), ('Запланировано', 'Запланировано'), ('Сделано', 'Сделано')], max_length=300, null=True, verbose_name='Отметка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать задачу')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_date', to='DatesApp.tasksdate', verbose_name='Сегодняшняя дата')),
            ],
            options={
                'verbose_name_plural': 'Список дел',
            },
        ),
    ]
